export const VERBS = [
  // ["abide", "abode", "abode", "соблюдать"],
  // ["arise", "arose", "arisen", "возникать"],
  // ["awake", "awoke", "awoken", "бодрствующий"],
  // ["bear", "bore", "borne", "нести"],
  // ["beat", "beat", "beaten", "бить"],
  // ["beget", "begot", "begotten", "зачать"],
  // ["bend", "bent", "bent", "согнуть"],
  // ["bet", "bet", "bet", "делать ставки"],
  // ["bind", "bound", "bound", "связывать"],
  // ["bite", "bit", "bitten", "кусать"],
  // ["bleed", "bled", "bled", "кровоточить"],
  // ["blow", "blew", "blown", "дуть"],
  // ["breed", "bred", "bred", "разводить"],
  // ["broadcast", "broadcast", "broadcast", "транслировать"],
  // ["build", "built", "built", "строить"],
  // ["burn", "burnt/burned", "burnt/burned", "сжечь"],
  // ["burst", "burst", "burst", "взрываться"],
  // ["can", "could", "… (been able)", "может"],
  // ["cling", "clung", "clung", "цепляться"],
  // ["creep", "crept", "crept", "ползать"],
  // ["deal", "dealt", "dealt", "иметь дело"],
  // ["dig", "dug", "dug", "копать"],
  // ["draw", "drew", "drawn", "рисовать"],
  // ["dream", "dreamt/dreamed", "dreamt/dreamed", "мечтать"],
  // ["feed", "fed", "fed", "кормить"],
  // ["feel", "felt", "felt", "чувствовать"],
  // ["fight", "fought", "fought", "бороться"],
  // ["forbid", "forbade", "forbidden", "запрещать"],
  // ["forgive", "forgave", "forgiven", "прощать"],
  // ["freeze", "froze", "frozen", "заморозить"],
  // ["grind", "ground", "ground", "молоть"],
  // ["hang", "hung", "hung", "повесить"],
  // ["hide", "hid", "hidden", "прятаться"],
  // ["hit", "hit", "hit", "ударить"],
  // ["hurt", "hurt", "hurt", "причинять боль"],
  // ["keep", "kept", "kept", "хранить"],
  // ["kneel", "knelt", "knelt", "преклонять колени"],
  // ["lay", "laid", "laid", "лежать"],
  // ["lead", "led", "led", "вести"],
  // ["lean", "leant/leaned", "leant/leaned", "наклоняться"],
  // ["lend", "lent", "lent", "давать в долг"],
  // ["lie (in bed)", "lay", "lain", "лежать"],
  // ["lie (to not tell the truth)", "lied", "lied", "ложь"],
  // ["light", "lit/lighted", "lit/lighted", "зажечь"],
  // ["mean", "meant", "meant", "иметь в виду"],
  // ["mow", "mowed", "mown/mowed", "косить"],
  // ["must", "had to", "...", "должен"],
  // ["overtake", "overtook", "overtaken", "обогнать"],
  // ["rise", "rose", "risen", "рост"],
  // ["saw", "sawed", "sawn/sawed", "пилить"],
  // ["sew", "sewed", "sewn/sewed", "шить"],
  // ["shake", "shook", "shaken", "трясти"],
  // ["shall", "should", "...", "должен"],
  // ["shed", "shed", "shed", "пролить"],
  // ["shine", "shone", "shone", "сиять"],
  // ["shoot", "shot", "shot", "выстрелить"],
  // ["show", "showed", "shown", "показывать"],
  // ["shrink", "shrank", "shrunk", "сокращаться"],
  // ["sink", "sank", "sunk", "тонуть"],
  // ["slide", "slid", "slid", "скользить"],
  // ["smell", "smelt", "smelt", "пахнуть"],
  // ["sow", "sowed", "sown/sowed", "сеять"],
  // ["spill", "spilt/spilled", "spilt/spilled", "разлить"],
  // ["spit", "spat", "spat", "плевать"],
  // ["spread", "spread", "spread", "распространять"],
  // ["steal", "stole", "stolen", "украсть"],
  // ["stick", "stuck", "stuck", "придерживаться"],
  // ["sting", "stung", "stung", "жалить"],
  // ["stink", "stank", "stunk", "вонять"],
  // ["strike", "struck", "struck", "бить"],
  // ["swear", "swore", "sworn", "ругаться"],
  // ["sweep", "swept", "swept", "мести"],
  // ["swell", "swelled", "swollen/swelled", "набухать"],
  // ["swing", "swung", "swung", "качать"],
  // ["tear", "tore", "torn", "рвать"],
  // ["wake", "woke", "woken", "разбудить"],
  // ["weep", "wept", "wept", "плакать"],
  // ["will", "would", "...", "желать"],
  // ["wind", "wound", "wound", "дуть"],

  ["be", "was/were", "been", "быть"],
  ["become", "became", "become", "становиться"],
  ["begin", "began", "begun", "начинать"],
  ["break", "broke", "broken", "перерыв"],
  ["bring", "brought", "brought", "приносить"],
  ["buy", "bought", "bought", "покупать"],
  ["catch", "caught", "caught", "ловить"],
  ["choose", "chose", "chosen", "выбирать"],
  ["come", "came", "come", "приходить"],
  ["cost", "cost", "cost", "стоимость"],
  ["cut", "cut", "cut", "резать"],
  ["do", "did", "done", "делать"],
  ["drink", "drank", "drunk", "пить"],
  ["drive", "drove", "driven", "водить"],
  ["eat", "ate", "eaten", "есть"],
  ["fall", "fell", "fallen", "падать"],
  ["find", "found", "found", "найти"],
  ["fly", "flew", "flown", "летать"],
  ["forget", "forgot", "forgotten", "забывать"],
  ["get", "got", "got", "получить"],
  ["give", "gave", "given", "давать"],
  ["go", "went", "gone", "идти"],
  ["grow", "grew", "grown", "расти"],
  ["have", "had", "had", "иметь"],
  ["hear", "heard", "heard", "слышать"],
  ["hold", "held", "held", "держать"],
  ["know", "knew", "known", "знать"],
  ["learn", "learnt/learned", "learnt/learned", "учиться"],
  ["leave", "left", "left", "покинуть"],
  ["lose", "lost", "lost", "терять"],
  ["make", "made", "made", "делать"],
  ["meet", "met", "met", "встречаться"],
  ["pay", "paid", "paid", "платить"],
  ["put", "put", "put", "класть"],
  ["read", "read", "read", "читать"],
  ["ride", "rode", "ridden", "ездить"],
  ["ring", "rang", "rung", "звонить"],
  ["run", "ran", "run", "бежать"],
  ["say", "said", "said", "сказать"],
  ["see", "saw", "seen", "увидеть"],
  ["sell", "sold", "sold", "продавать"],
  ["send", "sent", "sent", "отправлять"],
  ["sing", "sang", "sung", "петь"],
  ["sit", "sat", "sat", "сидеть"],
  ["sleep", "slept", "slept", "спать"],
  ["speak", "spoke", "spoken", "говорить"],
  ["spell", "spelt/spelled", "spelt/spelled", "произносить"],
  ["spend", "spent", "spent", "потратить"],
  ["stand", "stood", "stood", "стоять"],
  ["swim", "swam", "swum", "плавать"],
  ["take", "took", "taken", "принять"],
  ["teach", "taught", "taught", "учить"],
  ["tell", "told", "told", "сказать"],
  ["think", "thought", "thought", "думать"],
  ["throw", "threw", "thrown", "бросать"],
  ["understand", "understood", "understood", "понимать"],
  ["wear", "wore", "worn", "носить"],
  ["win", "won", "won", "побеждать"],
  ["write", "wrote", "written", "писать"],
];
